### ISSUE TITLE
Unable to recognize McGimp installations

### ISSUE THREAD

**Issue by nnewc** [SimulPiscator/GimpScan#1]
Hi,

I do not have upstream GIMP installed, but McGIMP from https://www.partha.com/. Can we add support for this?

McGimp is installed in this way:  /Applications/McGimp-2.10.20.app/Contents/Resources/lib/gimp/2.0/plug-ins/

**Comment by SimulPiscator** [comment]
Hi, I added support for paths that begin with `/Applications/McGimp`, and created a new release. Let me know whether it works for you.

**Comment by nnewc** [comment]
I tried click on the app and nothing happened so then I tried executing from the command line...

It seems some static libraries are missing:
```
dyld: Library not loaded: @rpath/libz.1.dylib
  Referenced from: /Users/nathannewcomb/Desktop/GimpScan.app/Contents/Frameworks/libfreetype.6.dylib
  Reason: image not found
Abort trap: 6
```

Currently on MacOS 10.15.7

**Comment by SimulPiscator** [comment]
On 10.15.7 it works for me, and I have a libz.1.dylib symlink in my path:
`% ls /usr/lib/libz*`
`/usr/lib/libz.1.1.3.dylib	/usr/lib/libz.1.2.8.dylib
/usr/lib/libz.1.2.11.dylib	/usr/lib/libz.1.dylib
/usr/lib/libz.1.2.5.dylib	/usr/lib/libz.dylib
`

**Comment by nnewc** [comment]
Yes I have the dylib as well in that directory. I just don't know how to troubleshoot it.

```
$ ls -la /usr/lib/libz*
lrwxr-xr-x  1 root  wheel    12B Nov 23  2020 /usr/lib/libz.1.1.3.dylib@ -> libz.1.dylib
lrwxr-xr-x  1 root  wheel    12B Nov 23  2020 /usr/lib/libz.1.2.11.dylib@ -> libz.1.dylib
lrwxr-xr-x  1 root  wheel    12B Nov 23  2020 /usr/lib/libz.1.2.5.dylib@ -> libz.1.dylib
lrwxr-xr-x  1 root  wheel    12B Nov 23  2020 /usr/lib/libz.1.2.8.dylib@ -> libz.1.dylib
-rwxr-xr-x  1 root  wheel   103K Jul  9 03:47 /usr/lib/libz.1.dylib*
lrwxr-xr-x  1 root  wheel    12B Nov 23  2020 /usr/lib/libz.dylib@ -> libz.1.dylib
```

**Comment by SimulPiscator** [comment]
In the attached version of GimpScan, I added libz to the "Frameworks" folder. Let me know if this works for you
[GimpScan.zip](https://github.com/SimulPiscator/GimpScan/files/9289207/GimpScan.zip)
.

**Comment by SimulPiscator** [comment]
I verified that release 0.41 of the GimpScan plugin works with McGimp on macOS 12.5.
